### ISSUE TITLE
Tree editor can't update subject

### ISSUE THREAD

**Issue by Integral** [substance/archivist-writer#15]
It fails here: https://github.com/substance/archivist-writer/blob/master/src/components/panels/subjects/edit_subject_reference_panel.js#L102
The id is in state, not in props...

**Comment by michael** [comment]
Function is not bound to this. Try:

``` js
doc.transaction({}, {updateSubjectReference: true}, function(tx) {
  tx.set([this.props.subjectReferenceId, "target"], subjectIds);
}.bind(this));
```

also note that `{updateSubjectReference: true}` should be the 2nd argument not the first.

**Comment by Integral** [comment]
@michael it's not a solution. Props have no subjectReferenceId, state have.
You can use two arguments for doc.transaction it will get eventdata as first argument if you have two arguments.

**Comment by michael** [comment]
ok need to investigate.. it should be props that have the subjectRefId.

**Comment by Integral** [comment]
same thing was here https://github.com/substance/archivist-writer/blob/master/src/components/panels/subjects/edit_subject_reference_panel.js#L117

**Comment by Integral** [comment]
also here https://github.com/substance/archivist-writer/blob/master/src/components/panels/subjects/subjects_panel.js#L68
and here https://github.com/substance/archivist-writer/blob/master/src/components/panels/subjects/subjects_panel.js#L117
(props instead of state)

**Comment by michael** [comment]
the thing is it should be props.. because the parent component passes those props. there should be a state derived from it because it complicates update usecases. will check this tomorrow

**Comment by michael** [comment]
This works now. As far as I can tell.
