### ISSUE TITLE
Not-a-Bug: can't add spaces in the beginning of row

### ISSUE THREAD

**Issue by Integral** [substance/archivist-writer#19]
Steps to reproduce:
1. Append any number of whitespaces to beginning of any row except first in paragraph.
2. Add then just other symbols. You will see spaces in next row.

**Comment by obuchtala** [comment]
I take this one.

**Comment by obuchtala** [comment]
Oh... I think we can't fix this... that is how it works in the browser (spaces are appended to previous line).

@michael do you agree?

**Comment by obuchtala** [comment]
It is different, when you explicitly added soft-break.

So, to achieve what you want, you add a soft-break, and then you can add spaces at the begin of line.

**Comment by obuchtala** [comment]
Closing as wont fix.

**Comment by michael** [comment]
I checked a bit, but i did not find consistent behavior. In some cases spaces go to the same line in other cases they go to the prev one.

Try just enabling contenteditable on a plain paragraph without styles

**Comment by obuchtala** [comment]
But essentially, it is not our part to layout text. So why should be able to control it -- beyond using explicit line-breaks.

**Comment by obuchtala** [comment]
Not to pre-wrap is not a solution, as then you would never see any multiple white-space.

**Comment by obuchtala** [comment]
I just tried LibreOffice: same behavior.

**Comment by obuchtala** [comment]
@Integral are you fine with my findings and decision?

**Comment by michael** [comment]
I'm fine with it yes. I understand it's not under our control.

Did you try this 15 spaces and navigate back? Also try alt left

If in previous line there is not enough space for all the spaces, they will be just cutted off and selection gets invisible when expanded.

However it's not under our control. So let's notfix it

**Comment by Integral** [comment]
@oliver---- Yes, I'm fine. As long as there are no bugs here.

**Comment by obuchtala** [comment]
It seems, the browser is turning off visibility for that extra-long white-space chunk.
When you continue to select backwards, it will start to show the selection at some point.
We can't fix that. and also I question the sanity of this use-case.
Still you can control it by adding a softbreak.

**Comment by obuchtala** [comment]
BTW: ctrl+left works fine here.

**Comment by michael** [comment]
Kk

**Comment by Integral** [comment]
No worries. I just thought that it is surface bug.

**Comment by obuchtala** [comment]
FYI: IE breaks the super-long spaces together with the last word.

**Comment by obuchtala** [comment]
Same for FF.

**Comment by michael** [comment]
FYI: Word also doesn't add spaces to active line. So I guess we don't have a bug here ,)

**Comment by Integral** [comment]
Come on! Please stop it!

**Comment by obuchtala** [comment]
No worries. Actually this issue made us aware of how editors work in the wild! :)

**Comment by obuchtala** [comment]
sorry ;)
