### ISSUE TITLE
Update all doc manipulation to use new transaction API.

### ISSUE THREAD

**Issue by michael** [substance/archivist-writer#8]
See here:

https://github.com/substance/archivist-writer/commit/0a687aa8a75683277db7e1f68947d7e35a481758

You can search for all occurences of `tx.` in the project and adapt. If you find things that need documentation just put it into the substance README.

**Comment by Integral** [comment]
Wow!

**Comment by michael** [comment]
when you get time. ;)

**Comment by michael** [comment]
i need to bring back all state transition stuff, and reintegrate some tools. like tagEntity Tool because we have a new tool API.

**Comment by Integral** [comment]
I mean, it's easier now!
