### ISSUE TITLE
Regression with Document.getContainerAnnotationsForSelection

### ISSUE THREAD

**Issue by michael** [substance/archivist-writer#9]
Here's the problem:

https://github.com/substance/substance/blob/5088f0baa6432d11e37a03d979a84b9a6c1d50e8/src/document/container_selection.js#L197

_coordinates function is not bound to this, so this.getContainer is not valid.

This is the call that breaks: 

https://github.com/substance/archivist-writer/blob/6d8ac9cb99df7caf8ac06d2a7bd3dbb9b5f65f24/src/state_handlers.js#L34

@oliver---- can you have a look?

**Comment by obuchtala** [comment]
Working on it.

**Comment by obuchtala** [comment]
What do I need to to reproduce?

**Comment by michael** [comment]
Uncomment this code:

https://github.com/substance/archivist-writer/blob/6d8ac9cb99df7caf8ac06d2a7bd3dbb9b5f65f24/src/state_handlers.js#L34-L46

**Comment by michael** [comment]
alternatively: activate subject_reference_tool, it will crash with the same error.

**Comment by obuchtala** [comment]
Got it. Will fix.

**Comment by obuchtala** [comment]
Should be fixed.

We need to check if the expand/truncate etc.. stuff is working properly for container selections.
